import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import { Toaster } from "sonner";
import Button from "@/components/Button";
import Section from "@/components/Section";
import Link from "next/link";
import Image from "next/image";
import classNames from "classnames";
import Logo from '../../../public/logo.svg';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digispot Shop",
  description: "Generated by create next app",
};

const categories = [
  {
    name: "Napoje",
    slug: "napoje"
  },
  {
    name: "Słodycze",
    slug: "slodycze"
  },
  {
    name: "Warzywa",
    slug: "warzywa"
  },
  {
    name: "Owoce",
    slug: "owoce"
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(montserrat.className, 'flex flex-col items-center')}>
        <Section
          className="flex justify-between py-6"
        >
          <Link href="/">
            <Image
              src={Logo}
              alt="Digispot Shop"
              style={{
                filter: "brightness(0)"
              }}
              className="h-10"
            />
          </Link>
          <div className="flex items-center gap-2">
            {categories.map(({ name, slug }) => (
              <Link
                key={slug}
                href={`/category/${slug}`}
                className="text-neutral-800 font-light"
              >
                {name}
              </Link>
            ))}
          </div>
        </Section>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
